---

- name: 'INSTALL | APT | Install curl packages'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ curl_repository_cache_valid_time }}"
  with_items: "{{ curl_packages }}"
