---

# Main tasks file for curl role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::curl'
    - 'role::curl::init'
